name: Playwright Automation 

on:
  push:
    branches: [ main ]

jobs:
  tests:
    name: Playwright Feature Execution
    runs-on: windows-latest
    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v3
    - name: Setting up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies    
      run: npm ci
    - name: Test execution
      run: npm run test
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results  